name: Release

on:
  push:
    schedule:
    - cron: '0 21 * * *'
    branches:
      - master

jobs:
  - name: 创建GitHub Release
    id: create_release
    uses: actions/create-release@latest
    env:
     GITHUB_TOKEN: ${{ secrets.DRAFTER_TOKEN }}
	with:
    tag_name: $date
    release_name: $date
    body: $date 的release
    draft: false
    prerelease: false